'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from "next-auth/react"
import MainNav from '../components/MainNav'
import SearchField from '../components/SearchField'
import LogIn from '../components/LogIn'
import Cart from '@/components/Cart'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className + ' h-[100vh]'}>
          <MainNav></MainNav>
          <SearchField></SearchField>
          <div className='md:flex md:my-4'>
            <LogIn></LogIn>
            <Cart></Cart>
          </div>
          {children}
          <Footer></Footer>
        </body>
      </html>
    </SessionProvider> 
  )
}
