'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from "next-auth/react"
import MainNav from '../components/MainNav'
import SearchField from '../components/SearchField'
import LogIn from '../components/LogIn'
import AddToCart from '@/components/AddToCart'
import RemoveFromCart from '../components/RemoveFromCart'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <MainNav></MainNav>
          <SearchField></SearchField>
          <LogIn></LogIn>
          {children}
          <AddToCart itemId={'itemId'} number={2}></AddToCart>
          <RemoveFromCart itemId={'itemId'} number={2}></RemoveFromCart>
        </body>
      </html>
    </SessionProvider> 
  )
}
